name: hobbyswap
recipe: drupal9
config:
  webroot: web
  php: '7.4'
  composer_version: 2
proxy:
  mailhog:
    - mail.hobbyswap.lndo.site
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        DRUSH_OPTIONS_URI: 'http://hobbyswap.lndo.site'
        DTT_BASE_URL: 'http://hobbyswap.lndo.site'
        BROWSERTEST_OUTPUT_DIRECTORY: '/app/web/sites/simpletest/browser_output'
        SYMFONY_DEPRECATIONS_HELPER: 'disabled'
        DTT_HTML_OUTPUT_DIRECTORY: '/app/web/sites/simpletest/browser_output'
        BROWSERTEST_OUTPUT_BASE_URL: 'http://hobbyswap.lndo.site/'
  database:
    creds:
      user: admin
      password: MEGAMIND
      database: hobbyswapdb
  node:
    type: node
    build:
      - 'cd /app/web/themes/custom/hobbyswap && npm install'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

tooling:
  composer:
    service: appserver
    cmd: '/usr/local/bin/composer'
  drush:
    service: appserver
    cmd: '/app/vendor/bin/drush'
  build-theme:
    service: node
    description: Performs a one-time Sass compilation.
    cmd: "cd /app/web/themes/custom/hobbyswap && $(npm bin)/sass sass/index.scss:css/index.css"
  watch-theme:
    service: node
    description: Watches for changes in index.scss and automatically compiles.
    cmd: "cd /app/web/themes/custom/hobbyswap && $(npm bin)/sass --watch sass/index.scss:css/index.css"
