<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function hs_dm_theme($existing, $type, $theme, $path){
  return[
    'hs_dm__inbox' => [
      'variables' => [
        'threads' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function hs_dm_preprocess(&$variables, $hook){
  if($hook === 'private_message_thread'){
    $variables['#attached']['library'] = 'hs_dm/private-message-thread';
  }
}
