<?php

/**
 * Implements hook_theme()
 */
function hs_square_theme($existing, $type, $theme, $path){
  return[
    'customer' => [
      'variables' => [
        'customer' => NULL,
        'cards' => NULL,
      ],
    ],
    'square__web_payment_form' => [
      'variables' => [
        'amount' => NULL
      ]
    ],
    'square__web_card_form' => [
      'variables' => []
    ],
    'card' => [
      'variables' => [
        'card' => NULL,
      ],
    ],
    'checkout_summary' => [
      'variables' => [
        'mode' => NULL,
        'requested' => NULL,
        'cost' => NULL,
      ]
    ]
  ];
}


/**
 * Implements hook_library_info_alter()
 */
function hs_square_library_info_alter(&$libraries, $extension){
  //Dynamically sets the url for Square's CDN
  if(isset($libraries['square'])){
    $environment = \Drupal::configFactory()->get('hs_square.settings')->get('environment');
    switch($environment){
      case 'production':
        $libraries['square']['js']['https://web.squarecdn.com/v0/square.js'] = [
          'type' => 'external',
          'minified' => 1
        ];
        break;
      case 'sandbox':
      default:
        $libraries['square']['js']['https://sandbox.web.squarecdn.com/v0/square.js'] = [
          'type' => 'external',
          'minified' => 1
        ];
    }
  }
}